development:
  adapter: mysql
  encoding: utf8
  database: zann_development
  username: zann
  password: n0lif3

test:
  adapter: mysql
  encoding: utf8
  database: zann_test
  username: zann
  password: n0lif3
  
production:
  adapter: mysql
  encoding: utf8
  database: zann_production
  username: zann
  password: n0lif3