development:
  adapter: jdbc
  driver: org.apache.derby.jdbc.ClientDriver
  url: jdbc:derby://localhost:1527/zann_development
  username: zann
  password: Iloveemc1314

test:
  adapter: jdbc
  driver: org.apache.derby.jdbc.ClientDriver
  url: jdbc:derby://localhost:1527/zann_test
  username: zann
  password: Iloveemc1314
  
production:
  adapter: jdbc
  driver: org.apache.derby.jdbc.ClientDriver
  url: jdbc:derby://localhost:1527/zann_production
  username: zann
  password: Iloveemc1314