development:
  adapter: jdbcmysql
  encoding: utf8
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/zann_development
  username: zann
  password: n0lif3

test:
  adapter: jdbcmysql
  encoding: utf8
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/zann_test
  username: zann
  password: n0lif3
  
production:
  adapter: jdbcmysql
  encoding: utf8
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/zann_production
  username: zann
  password: n0lif3
